baseURL = "https://www.xli.me"
languageCode = "zh-Hans"
title = "Mr Fox"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true
enableEmoji = true

[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "标签"
  weight = 20
  identifier = "tags"
  url = "/tags/"

[params]
  author = "xli"
  avatar = "/img/avatar.jpg"
  seotitle = "呓语~"
  subtitle = "brief is life but love is long~"
  description = "brief is life but love is long~"
  paginate = 20

  email = "kaidiren@gmail.com"
  github = "kaidiren"
